name: Auto Merge PRs

on:
  pull_request:
    branches:
      - Projetps

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto merge PR
        uses: pascalgn/automerge-action@v0.15.0
        with:
          merge_method: merge
          github_token: ${{ secrets.GITHUB_TOKEN }}
