name: Auto Merge PRs

on:
  pull_request:
    branches:
      - Projetps

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        uses: peter-evans/enable-auto-merge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
